name: nostd-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror"
    - name: Make
      working-directory: ${{github.workspace}}/build
      run: make -j
      
    - name: Test Storage
      working-directory: ${{github.workspace}}/build
      run: ./test_storage
      
    - name: Test Array
      working-directory: ${{github.workspace}}/build
      run: ./test_array
      
